--- #YAML:1.0
name:                Muldis-DB
version:             0.6.0
abstract:            Full-featured truly relational DBMS in Perl
license:             lgpl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Darren Duncan <perl@DarrenDuncan.net>
